sudo : required
services:
    - docker

before_install:
    - docker build -t philmat-ai/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true philmat-ai/docker-react npm run test -- --coverage

